$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: f1-predictions-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
conda_file: ../environment.yml
description: Environment for training F1 predictions model.
